# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 가이랏
email: ai.devveloper@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  AI 연구자 및 개발자 - 딥러닝 애호가
baseurl: "/" # the subpath of your site, e.g. /blog
url: "aidevveloper.github.io" # the base hostname & protocol for your site

social:
  - title: linkedin
    url: https://www.linkedin.com/in/ai-devveloper/ 
  - title: github
    url: https://github.com/aidevveloper


# Address information
location: Seoul, South Korea
address:

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

# Defaults
defaults:
  -
    scope:
      path: "_posts"
    values:
      thumb_image_url: "assets/test_post/images/1-submarine.png"

# Particles in the background
show_particles: true
