title: 가이랏
email: ai.devveloper@gmail.com
description: > 
  AI 연구자 및 개발자 - 딥러닝 애호가
baseurl: "/"
url: "" 

social:
  - title: linkedin
    url: https://www.linkedin.com/in/ai-devveloper/ 
  - title: github
    url: https://github.com/aidevveloper

location: Seoul, South Korea
address:

markdown: kramdown
kramdown:
  parse_block_html: true

defaults:
  -
    scope:
      path: "_posts"
    values:
      thumb_image_url: "assets/test_post/images/1-submarine.png"

show_particles: true
