/*

 The MIT License (MIT)
 Copyright (c) 2018 Javan Makhmali

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.

 /

/*
Details Element Polyfill 2.4.0
Copyright ? 2019 Javan Makhmali
*/
(function(){function a(){var k=document.createElement("details").constructor.prototype,m=k.setAttribute,q=k.removeAttribute,w=Object.getOwnPropertyDescriptor(k,"open");Object.defineProperties(k,{open:{get:function(){if("DETAILS"==this.tagName)return this.hasAttribute("open");if(w&&w.get)return w.get.call(this)},set:function(u){if("DETAILS"==this.tagName)return u?this.setAttribute("open",""):this.removeAttribute("open");if(w&&w.set)return w.set.call(this,u)}},setAttribute:{value:function(u,y){var x=
this;if("open"==u&&"DETAILS"==this.tagName){var z=this.hasAttribute("open");u=m.call(x,u,y);z||((z=this.querySelector("summary"))&&z.setAttribute("aria-expanded",!0),l(this));return u}return m.call(x,u,y)}},removeAttribute:{value:function(u){var y=this;if("open"==u&&"DETAILS"==this.tagName){var x=this.hasAttribute("open");u=q.call(y,u);x&&((x=this.querySelector("summary"))&&x.setAttribute("aria-expanded",!1),l(this));return u}return q.call(y,u)}}})}function b(){g(function(k){k.hasAttribute("open")?
k.removeAttribute("open"):k.setAttribute("open","")})}function c(){window.MutationObserver?(new MutationObserver(function(k){v.call(k,function(m){var q=m.target;m=m.attributeName;"DETAILS"==q.tagName&&"open"==m&&l(q)})})).observe(document.documentElement,{attributes:!0,subtree:!0}):g(function(k){var m=k.getAttribute("open");setTimeout(function(){var q=k.getAttribute("open");m!=q&&l(k)},1)})}function d(){e(document);window.MutationObserver?(new MutationObserver(function(k){v.call(k,function(m){v.call(m.addedNodes,
e)})})).observe(document.documentElement,{subtree:!0,childList:!0}):document.addEventListener("DOMNodeInserted",function(k){e(k.target)})}function e(k){n(k,"SUMMARY").forEach(function(m){var q=r(m,"DETAILS");m.setAttribute("aria-expanded",q.hasAttribute("open"));m.hasAttribute("tabindex")||m.setAttribute("tabindex","0");m.hasAttribute("role")||m.setAttribute("role","button")})}function f(k){return!(k.defaultPrevented||k.ctrlKey||k.metaKey||k.shiftKey||k.target.isContentEditable)}function g(k){window.addEventListener("click",
function(m){f(m)&&1>=m.which&&(m=r(m.target,"SUMMARY"))&&m.parentNode&&"DETAILS"==m.parentNode.tagName&&k(m.parentNode)},!1);window.addEventListener("keydown",function(m){if(f(m)&&(13==m.keyCode||32==m.keyCode)){var q=r(m.target,"SUMMARY");q&&q.parentNode&&"DETAILS"==q.parentNode.tagName&&(k(q.parentNode),m.preventDefault())}},!1)}function l(k){var m=document.createEvent("Event");m.initEvent("toggle",!1,!1);k.dispatchEvent(m)}function n(k,m){return(k.tagName==m?[k]:[]).concat("function"==typeof k.getElementsByTagName?
A.call(k.getElementsByTagName(m)):[])}function r(k,m){if("function"==typeof k.closest)return k.closest(m);for(;k;){if(k.tagName==m)return k;k=k.parentNode}}var h=document.createElement("details"),p="undefined"!=typeof HTMLDetailsElement&&h instanceof HTMLDetailsElement;h={open:"open"in h||p,toggle:"ontoggle"in h};var t=[],v=t.forEach,A=t.slice;h.open||(document.head.insertAdjacentHTML("afterbegin",'<style>\ndetails, summary {\n  display: block;\n}\ndetails:not([open]) > *:not(summary) {\n  display: none;\n}\nsummary::before {\n  content: "\u25ba";\n  padding-right: 0.3rem;\n  font-size: 0.6rem;\n  cursor: default;\n}\n[open] > summary::before {\n  content: "\u25bc";\n}\n</style>'),
a(),b(),d());h.open&&!h.toggle&&c()})();/*

 Copyright 2017 Google Inc. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS-IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
const RATINGS={PASS:{label:"pass",minScore:.9},AVERAGE:{label:"average",minScore:.5},FAIL:{label:"fail"},ERROR:{label:"error"}};
class Util{static prepareReportResult(a){const b=JSON.parse(JSON.stringify(a));b.configSettings.locale||(b.configSettings.locale="en");for(const c of Object.values(b.audits)){if("not_applicable"===c.scoreDisplayMode||"not-applicable"===c.scoreDisplayMode)c.scoreDisplayMode="notApplicable";if(c.details){if(void 0===c.details.type||"diagnostic"===c.details.type)c.details.type="debugdata";if("filmstrip"===c.details.type)for(const d of c.details.items)d.data.startsWith("data:image/jpeg;base64,")||(d.data=
"data:image/jpeg;base64,"+d.data)}}Util.setNumberDateLocale(b.configSettings.locale);b.i18n&&b.i18n.rendererFormattedStrings&&Util.updateAllUIStrings(b.i18n.rendererFormattedStrings);if("object"!==typeof b.categories)throw Error("No categories provided.");for(const c of Object.values(b.categories))c.auditRefs.forEach(d=>{const e=b.audits[d.id];d.result=e;b.stackPacks&&b.stackPacks.forEach(f=>{f.descriptions[d.id]&&(d.stackPacks=d.stackPacks||[],d.stackPacks.push({title:f.title,iconDataURL:f.iconDataURL,
description:f.descriptions[d.id]}))})});return b}static updateAllUIStrings(a){for(const [b,c]of Object.entries(a))Util.UIStrings[b]=c}static showAsPassed(a){switch(a.scoreDisplayMode){case "manual":case "notApplicable":return!0;case "error":case "informative":return!1;default:return Number(a.score)>=RATINGS.PASS.minScore}}static calculateRating(a,b){if("manual"===b||"notApplicable"===b)return RATINGS.PASS.label;if("error"===b)return RATINGS.ERROR.label;if(null===a)return RATINGS.FAIL.label;b=RATINGS.FAIL.label;
a>=RATINGS.PASS.minScore?b=RATINGS.PASS.label:a>=RATINGS.AVERAGE.minScore&&(b=RATINGS.AVERAGE.label);return b}static formatNumber(a,b=.1){a=Math.round(a/b)*b;return a.toLocaleString(Util.numberDateLocale)}static formatBytesToKB(a,b=.1){a=(Math.round(a/1024/b)*b).toLocaleString(Util.numberDateLocale);return`${a}${"\u00a0"}KB`}static formatMilliseconds(a,b=10){a=Math.round(a/b)*b;return`${a.toLocaleString(Util.numberDateLocale)}${"\u00a0"}ms`}static formatSeconds(a,b=.1){a=Math.round(a/1E3/b)*b;return`${a.toLocaleString(Util.numberDateLocale)}${"\u00a0"}s`}static formatDateTime(a){const b=
{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"numeric",timeZoneName:"short"};let c=new Intl.DateTimeFormat(Util.numberDateLocale,b);const d=c.resolvedOptions().timeZone;d&&"etc/unknown"!==d.toLowerCase()||(b.timeZone="UTC",c=new Intl.DateTimeFormat(Util.numberDateLocale,b));return c.format(new Date(a))}static formatDuration(a){let b=a/1E3;if(0===Math.round(b))return"None";const c=[],d={d:86400,h:3600,m:60,s:1};Object.keys(d).forEach(e=>{const f=d[e],g=Math.floor(b/f);0<g&&(b-=
g*f,c.push(`${g}\xa0${e}`))});return c.join(" ")}static getURLDisplayName(a,b){b=b||{numPathParts:void 0,preserveQuery:void 0,preserveHost:void 0};const c=void 0!==b.numPathParts?b.numPathParts:2,d=void 0!==b.preserveQuery?b.preserveQuery:!0,e=b.preserveHost||!1;if("about:"===a.protocol||"data:"===a.protocol)b=a.href;else{b=a.pathname;const f=b.split("/").filter(g=>g.length);c&&f.length>c&&(b="\u2026"+f.slice(-1*c).join("/"));e&&(b=`${a.host}/${b.replace(/^\//,"")}`);d&&(b=`${b}${a.search}`)}b=b.replace(/([a-f0-9]{7})[a-f0-9]{13}[a-f0-9]*/g,
"$1\u2026");b=b.replace(/([a-zA-Z0-9-_]{9})(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])[a-zA-Z0-9-_]{10,}/g,"$1\u2026");b=b.replace(/(\d{3})\d{6,}/g,"$1\u2026");b=b.replace(/\u2026+/g,"\u2026");64<b.length&&b.includes("?")&&(b=b.replace(/\?([^=]*)(=)?.*/,"?$1$2\u2026"),64<b.length&&(b=b.replace(/\?.*/,"?\u2026")));64<b.length&&(a=b.lastIndexOf("."),b=0<=a?b.slice(0,63-(b.length-a))+`${"\u2026"}${b.slice(a)}`:b.slice(0,63)+"\u2026");return b}static parseURL(a){a=new URL(a);return{file:Util.getURLDisplayName(a),
hostname:a.hostname,origin:a.origin}}static getEnvironmentDisplayValues(a){a=Util.getEmulationDescriptions(a);return[{name:"Device",description:a.deviceEmulation},{name:"Network throttling",description:a.networkThrottling},{name:"CPU throttling",description:a.cpuThrottling}]}static getEmulationDescriptions(a){let b;let c;var d=a.throttling;switch(a.throttlingMethod){case "provided":d=b="Provided by environment";c="No throttling applied";break;case "devtools":{const {cpuSlowdownMultiplier:f,requestLatencyMs:g}=
d;b=`${Util.formatNumber(f)}x slowdown (DevTools)`;d=`${Util.formatNumber(g)}${"\u00a0"}ms HTTP RTT, `+`${Util.formatNumber(d.downloadThroughputKbps)}${"\u00a0"}Kbps down, `+`${Util.formatNumber(d.uploadThroughputKbps)}${"\u00a0"}Kbps up (DevTools)`;c="Throttled Slow 4G network";break}case "simulate":{const {cpuSlowdownMultiplier:f,rttMs:g,throughputKbps:l}=d;b=`${Util.formatNumber(f)}x slowdown (Simulated)`;d=`${Util.formatNumber(g)}${"\u00a0"}ms TCP RTT, `+`${Util.formatNumber(l)}${"\u00a0"}Kbps throughput (Simulated)`;
c="Simulated Slow 4G network";break}default:c=d=b="Unknown"}let e="No emulation";"mobile"===a.emulatedFormFactor&&(e="Emulated Nexus 5X");"desktop"===a.emulatedFormFactor&&(e="Emulated Desktop");return{deviceEmulation:e,cpuThrottling:b,networkThrottling:d,summary:`${e}, ${c}`}}static setNumberDateLocale(a){Util.numberDateLocale=a;"en-XA"===Util.numberDateLocale&&(Util.numberDateLocale="de")}static filterRelevantLines(a,b,c){if(0===b.length)return a.slice(0,2*c+1);const d=new Set;b=b.sort((e,f)=>(e.lineNumber||
0)-(f.lineNumber||0));b.forEach(({lineNumber:e})=>{var f=e-c;for(e+=c;1>f;)f++,e++;for(d.has(f-3-1)&&(f-=3);f<=e;f++){const g=f;d.add(g)}});return a.filter(e=>d.has(e.lineNumber))}static isPluginCategory(a){return a.startsWith("lighthouse-plugin-")}}Util.numberDateLocale="en";
Util.UIStrings={varianceDisclaimer:"Values are estimated and may vary. The performance score is [based only on these metrics](https://github.com/GoogleChrome/lighthouse/blob/d2ec9ffbb21de9ad1a0f86ed24575eda32c796f0/docs/scoring.md#how-are-the-scores-weighted).",opportunityResourceColumnLabel:"Opportunity",opportunitySavingsColumnLabel:"Estimated Savings",errorMissingAuditInfo:"Report error: no audit information",errorLabel:"Error!",warningHeader:"Warnings: ",auditGroupExpandTooltip:"Show audits",
warningAuditsGroupTitle:"Passed audits but with warnings",passedAuditsGroupTitle:"Passed audits",notApplicableAuditsGroupTitle:"Not applicable",manualAuditsGroupTitle:"Additional items to manually check",toplevelWarningsMessage:"There were issues affecting this run of Lighthouse:",crcInitialNavigation:"Initial Navigation",crcLongestDurationLabel:"Maximum critical path latency:",snippetExpandButtonLabel:"Expand snippet",snippetCollapseButtonLabel:"Collapse snippet",lsPerformanceCategoryDescription:"[Lighthouse](https://developers.google.com/web/tools/lighthouse/) analysis of the current page on an emulated mobile network. Values are estimated and may vary.",
labDataTitle:"Lab Data",thirdPartyResourcesLabel:"Show 3rd-party resources"};"undefined"!==typeof module&&module.exports?module.exports=Util:self.Util=Util;class DOM{constructor(a){this._document=a;this._lighthouseChannel="unknown"}createElement(a,b,c={}){const d=this._document.createElement(a);b&&(d.className=b);Object.keys(c).forEach(e=>{const f=c[e];"undefined"!==typeof f&&d.setAttribute(e,f)});return d}createFragment(){return this._document.createDocumentFragment()}createChildOf(a,b,c,d){b=this.createElement(b,c,d);a.appendChild(b);return b}cloneTemplate(a,b){b=b.querySelector(a);if(!b)throw Error(`Template not found: template${a}`);a=this._document.importNode(b.content,
!0);b.hasAttribute("data-stamped")&&this.findAll("style",a).forEach(c=>c.remove());b.setAttribute("data-stamped","true");return a}resetTemplates(){this.findAll("template[data-stamped]",this._document).forEach(a=>{a.removeAttribute("data-stamped")})}convertMarkdownLinkSnippets(a){const b=this.createElement("span");for(a=a.split(/\[([^\]]*?)\]\((https?:\/\/.*?)\)/g);a.length;){const [d,e,f]=a.splice(0,3);b.appendChild(this._document.createTextNode(d));if(e&&f){const g=new URL(f);var c="https://developers.google.com";
g.origin===c&&(g.searchParams.set("utm_source","lighthouse"),g.searchParams.set("utm_medium",this._lighthouseChannel));c=this.createElement("a");c.rel="noopener";c.target="_blank";c.textContent=e;c.href=g.href;b.appendChild(c)}}return b}convertMarkdownCodeSnippets(a){const b=this.createElement("span");for(a=a.split(/`(.*?)`/g);a.length;){const [c,d]=a.splice(0,2);b.appendChild(this._document.createTextNode(c));if(d){const e=this.createElement("code");e.textContent=d;b.appendChild(e)}}return b}document(){return this._document}isDevTools(){return!!this._document.querySelector(".lh-devtools")}find(a,
b){b=b.querySelector(a);if(null===b)throw Error(`query ${a} not found`);return b}findAll(a,b){return Array.from(b.querySelectorAll(a))}}"undefined"!==typeof module&&module.exports?module.exports=DOM:self.DOM=DOM;const URL_PREFIXES=["http://","https://","data:"];
class DetailsRenderer{constructor(a){this._dom=a}setTemplateContext(a){this._templateContext=a}render(a){switch(a.type){case "filmstrip":return this._renderFilmstrip(a);case "list":return this._renderList(a);case "table":return this._renderTable(a);case "criticalrequestchain":return CriticalRequestChainRenderer.render(this._dom,this._templateContext,a,this);case "opportunity":return this._renderTable(a);case "screenshot":case "debugdata":return null;default:throw a=a.type,Error(`Unknown type: ${a}`);
}}_renderBytes(a){a=Util.formatBytesToKB(a.value,a.granularity);return this._renderText(a)}_renderMilliseconds(a){let b=Util.formatMilliseconds(a.value,a.granularity);"duration"===a.displayUnit&&(b=Util.formatDuration(a.value));return this._renderText(b)}renderTextURL(a){let b,c;try{var d=Util.parseURL(a);var e="/"===d.file?d.origin:d.file;b="/"===d.file?"":`(${d.hostname})`;c=a}catch(f){e=a}d=this._dom.createElement("div","lh-text__url");d.appendChild(this._renderLink({text:e,url:a}));b&&(e=this._renderText(b),
e.classList.add("lh-text__url-host"),d.appendChild(e));c&&(d.title=a,d.dataset.url=a);return d}_renderLink(a){var b=["https:","http:"];let c;try{c=new URL(a.url)}catch(d){}if(!c||!b.includes(c.protocol))return this._renderText(a.text);b=this._dom.createElement("a");b.rel="noopener";b.target="_blank";b.textContent=a.text;b.href=c.href;return b}_renderText(a){const b=this._dom.createElement("div","lh-text");b.textContent=a;return b}_renderNumeric(a){const b=this._dom.createElement("div","lh-numeric");
b.textContent=a;return b}_renderThumbnail(a){const b=this._dom.createElement("img","lh-thumbnail");b.src=a;b.title=a;b.alt="";return b}_renderTableValue(a,b){if("undefined"===typeof a||null===a)return null;if("object"===typeof a)switch(a.type){case "code":return this._renderCode(a.value);case "link":return this._renderLink(a);case "node":return this.renderNode(a);case "url":return this.renderTextURL(a.value);default:throw Error(`Unknown valueType: ${a.type}`);}switch(b.valueType){case "bytes":return a=
Number(a),this._renderBytes({value:a,granularity:1});case "code":return a=String(a),this._renderCode(a);case "ms":return a={value:Number(a),granularity:b.granularity,displayUnit:b.displayUnit},this._renderMilliseconds(a);case "numeric":return a=String(a),this._renderNumeric(a);case "text":return a=String(a),this._renderText(a);case "thumbnail":return a=String(a),this._renderThumbnail(a);case "timespanMs":return a=Number(a),this._renderMilliseconds({value:a});case "url":{const c=String(a);return URL_PREFIXES.some(d=>
c.startsWith(d))?this.renderTextURL(c):this._renderCode(c)}default:throw Error(`Unknown valueType: ${b.valueType}`);}}_getCanonicalizedTableHeadings(a){return"opportunity"===a.type?a.headings:a.headings.map(b=>({key:b.key,label:b.text,valueType:b.itemType,displayUnit:b.displayUnit,granularity:b.granularity}))}_renderTable(a){if(!a.items.length)return this._dom.createElement("span");const b=this._dom.createElement("table","lh-table");var c=this._dom.createChildOf(b,"thead"),d=this._dom.createChildOf(c,
"tr");c=this._getCanonicalizedTableHeadings(a);for(var e of c){var f=e.valueType||"text";f=`lh-table-column--${f}`;const g=this._dom.createElement("div","lh-text");g.textContent=e.label;this._dom.createChildOf(d,"th",f).appendChild(g)}e=this._dom.createChildOf(b,"tbody");for(const g of a.items){a=this._dom.createChildOf(e,"tr");for(const l of c)d=g[l.key],(d=this._renderTableValue(d,l))?(f=`lh-table-column--${l.valueType}`,this._dom.createChildOf(a,"td",f).appendChild(d)):this._dom.createChildOf(a,
"td","lh-table-column--empty")}return b}_renderList(a){const b=this._dom.createElement("div","lh-list");a.items.forEach(c=>{c=SnippetRenderer.render(this._dom,this._templateContext,c,this);b.appendChild(c)});return b}renderNode(a){const b=this._dom.createElement("span","lh-node");if(a.nodeLabel){var c=this._dom.createElement("div");c.textContent=a.nodeLabel;b.appendChild(c)}a.snippet&&(c=this._dom.createElement("div"),c.classList.add("lh-node__snippet"),c.textContent=a.snippet,b.appendChild(c));a.selector&&
(b.title=a.selector);a.path&&b.setAttribute("data-path",a.path);a.selector&&b.setAttribute("data-selector",a.selector);a.snippet&&b.setAttribute("data-snippet",a.snippet);return b}_renderFilmstrip(a){const b=this._dom.createElement("div","lh-filmstrip");for(const c of a.items)a=this._dom.createChildOf(b,"div","lh-filmstrip__frame"),this._dom.createChildOf(a,"img","lh-filmstrip__thumbnail",{src:c.data,alt:"Screenshot"});return b}_renderCode(a){const b=this._dom.createElement("pre","lh-code");b.textContent=
a;return b}}"undefined"!==typeof module&&module.exports?module.exports=DetailsRenderer:self.DetailsRenderer=DetailsRenderer;class CriticalRequestChainRenderer{static initTree(a){var b=0;const c=Object.keys(a);0<c.length&&(b=a[c[0]],b=b.request.startTime);return{tree:a,startTime:b,transferSize:0}}static createSegment(a,b,c,d,e,f){const g=a[b];a=Object.keys(a);b=a.indexOf(b)===a.length-1;a=!!g.children&&0<Object.keys(g.children).length;e=Array.isArray(e)?e.slice(0):[];"undefined"!==typeof f&&e.push(!f);return{node:g,isLastChild:b,hasChildren:a,startTime:c,transferSize:d+g.request.transferSize,treeMarkers:e}}static createChainNode(a,
b,c,d){b=a.cloneTemplate("#tmpl-lh-crc__chains",b);a.find(".crc-node",b).setAttribute("title",c.node.request.url);const e=a.find(".crc-node__tree-marker",b);c.treeMarkers.forEach(g=>{g?e.appendChild(a.createElement("span","tree-marker vert")):e.appendChild(a.createElement("span","tree-marker"));e.appendChild(a.createElement("span","tree-marker"))});c.isLastChild?e.appendChild(a.createElement("span","tree-marker up-right")):e.appendChild(a.createElement("span","tree-marker vert-right"));e.appendChild(a.createElement("span",
"tree-marker right"));c.hasChildren?e.appendChild(a.createElement("span","tree-marker horiz-down")):e.appendChild(a.createElement("span","tree-marker right"));var f=c.node.request.url;f=d.renderTextURL(f);d=a.find(".crc-node__tree-value",b);d.appendChild(f);if(!c.hasChildren){const {startTime:g,endTime:l,transferSize:n}=c.node.request;c=a.createElement("span","crc-node__chain-duration");c.textContent=" - "+Util.formatMilliseconds(1E3*(l-g))+", ";f=a.createElement("span","crc-node__chain-duration");
f.textContent=Util.formatBytesToKB(n,.01);d.appendChild(c);d.appendChild(f)}return b}static buildTree(a,b,c,d,e,f){d.appendChild(CriticalRequestChainRenderer.createChainNode(a,b,c,f));if(c.node.children)for(const g of Object.keys(c.node.children)){const l=CriticalRequestChainRenderer.createSegment(c.node.children,g,c.startTime,c.transferSize,c.treeMarkers,c.isLastChild);CriticalRequestChainRenderer.buildTree(a,b,l,d,e,f)}}static render(a,b,c,d){b=a.cloneTemplate("#tmpl-lh-crc",b);const e=a.find(".lh-crc",
b);a.find(".crc-initial-nav",b).textContent=Util.UIStrings.crcInitialNavigation;a.find(".lh-crc__longest_duration_label",b).textContent=Util.UIStrings.crcLongestDurationLabel;a.find(".lh-crc__longest_duration",b).textContent=Util.formatMilliseconds(c.longestChain.duration);const f=CriticalRequestChainRenderer.initTree(c.chains);for(const g of Object.keys(f.tree)){const l=CriticalRequestChainRenderer.createSegment(f.tree,g,f.startTime,f.transferSize);CriticalRequestChainRenderer.buildTree(a,b,l,e,
c,d)}return a.find(".lh-crc-container",b)}}"undefined"!==typeof module&&module.exports?module.exports=CriticalRequestChainRenderer:self.CriticalRequestChainRenderer=CriticalRequestChainRenderer;class CategoryRenderer{constructor(a,b){this.dom=a;this.detailsRenderer=b;this.templateContext=this.dom.document();this.detailsRenderer.setTemplateContext(this.templateContext)}get _clumpTitles(){return{warning:Util.UIStrings.warningAuditsGroupTitle,manual:Util.UIStrings.manualAuditsGroupTitle,passed:Util.UIStrings.passedAuditsGroupTitle,notApplicable:Util.UIStrings.notApplicableAuditsGroupTitle}}renderAudit(a){const b=this.dom.cloneTemplate("#tmpl-lh-audit",this.templateContext);return this.populateAuditValues(a,
b)}populateAuditValues(a,b){const c=this.dom.find(".lh-audit",b);c.id=a.result.id;var d=a.result.scoreDisplayMode;a.result.displayValue&&(this.dom.find(".lh-audit__display-text",c).textContent=a.result.displayValue);b=this.dom.find(".lh-audit__title",c);b.appendChild(this.dom.convertMarkdownCodeSnippets(a.result.title));this.dom.find(".lh-audit__description",c).appendChild(this.dom.convertMarkdownLinkSnippets(a.result.description));a.stackPacks&&a.stackPacks.forEach(f=>{const g=this.dom.createElement("div");
g.classList.add("lh-audit__stackpack");const l=this.dom.createElement("img");l.classList.add("lh-audit__stackpack__img");l.src=f.iconDataURL;l.alt=f.title;g.appendChild(l);g.appendChild(this.dom.convertMarkdownLinkSnippets(f.description));this.dom.find(".lh-audit__stackpacks",c).appendChild(g)});const e=this.dom.find("details",c);if(a.result.details){const f=this.detailsRenderer.render(a.result.details);f&&(f.classList.add("lh-details"),e.appendChild(f))}this.dom.find(".lh-chevron-container",c).appendChild(this._createChevron());
this._setRatingClass(c,a.result.score,d);"error"===a.result.scoreDisplayMode?(c.classList.add("lh-audit--error"),d=this.dom.find(".lh-audit__display-text",c),d.textContent=Util.UIStrings.errorLabel,d.classList.add("tooltip-boundary"),d=this.dom.createChildOf(d,"div","tooltip tooltip--error"),d.textContent=a.result.errorMessage||Util.UIStrings.errorMissingAuditInfo):a.result.explanation&&(d=this.dom.createChildOf(b,"div","lh-audit-explanation"),d.textContent=a.result.explanation);a=a.result.warnings;
if(!a||0===a.length)return c;b=this.dom.createChildOf(b,"div","lh-warnings");this.dom.createChildOf(b,"span").textContent=Util.UIStrings.warningHeader;if(1===a.length)b.appendChild(this.dom.document().createTextNode(a.join("")));else{b=this.dom.createChildOf(b,"ul");for(const f of a)a=this.dom.createChildOf(b,"li"),a.textContent=f}return c}_createChevron(){var a=this.dom.cloneTemplate("#tmpl-lh-chevron",this.templateContext);return a=this.dom.find(".lh-chevron",a)}_setRatingClass(a,b,c){b=Util.calculateRating(b,
c);a.classList.add(`lh-audit--${c.toLowerCase()}`);"informative"!==c&&a.classList.add(`lh-audit--${b}`);return a}renderCategoryHeader(a,b){const c=this.dom.cloneTemplate("#tmpl-lh-category-header",this.templateContext),d=this.dom.find(".lh-score__gauge",c);b=this.renderScoreGauge(a,b);d.appendChild(b);a.description&&(a=this.dom.convertMarkdownLinkSnippets(a.description),this.dom.find(".lh-category-header__description",c).appendChild(a));return c.firstElementChild}renderAuditGroup(a){const b=this.dom.createElement("div",
"lh-audit-group"),c=this.dom.createElement("div","lh-audit-group__header");this.dom.createChildOf(c,"span","lh-audit-group__title").textContent=a.title;a.description&&(a=this.dom.convertMarkdownLinkSnippets(a.description),a.classList.add("lh-audit-group__description"),c.appendChild(a));b.appendChild(c);return b}_renderGroupedAudits(a,b){var c=new Map;c.set("NotAGroup",[]);for(var d of a){a=d.group||"NotAGroup";const e=c.get(a)||[];e.push(d);c.set(a,e)}d=[];for(const [e,f]of c)if("NotAGroup"===e)for(const g of f)d.push(this.renderAudit(g));
else{c=b[e];c=this.renderAuditGroup(c);for(const g of f)c.appendChild(this.renderAudit(g));c.classList.add(`lh-audit-group--${e}`);d.push(c)}return d}renderUnexpandableClump(a,b){const c=this.dom.createElement("div");a=this._renderGroupedAudits(a,b);a.forEach(d=>c.appendChild(d));return c}renderClump(a,{auditRefs:b,description:c}){var d=this.dom.cloneTemplate("#tmpl-lh-clump",this.templateContext);d=this.dom.find(".lh-clump",d);"warning"===a&&d.setAttribute("open","");var e=this.dom.find(".lh-audit-group__summary",
d);e=e.appendChild(this._createChevron());e.title=Util.UIStrings.auditGroupExpandTooltip;e=this.dom.find(".lh-audit-group__header",d);const f=this._clumpTitles[a];this.dom.find(".lh-audit-group__title",e).textContent=f;c&&(c=this.dom.convertMarkdownLinkSnippets(c),c.classList.add("lh-audit-group__description"),e.appendChild(c));c=this.dom.find(".lh-audit-group__itemcount",d);c.textContent=`(${b.length})`;b=b.map(this.renderAudit.bind(this));d.append(...b);d.classList.add(`lh-clump--${a.toLowerCase()}`);
return d}setTemplateContext(a){this.templateContext=a;this.detailsRenderer.setTemplateContext(a)}renderScoreGauge(a){const b=this.dom.cloneTemplate("#tmpl-lh-gauge",this.templateContext);var c=this.dom.find(".lh-gauge__wrapper",b);c.href=`#${a.id}`;c.classList.add(`lh-gauge__wrapper--${Util.calculateRating(a.score)}`);Util.isPluginCategory(a.id)&&c.classList.add("lh-gauge__wrapper--plugin");c=Number(a.score);var d=this.dom.find(".lh-gauge",b);if(d=d.querySelector(".lh-gauge-arc"))d.style.strokeDasharray=
`${352*c} 352`;c=Math.round(100*c);d=this.dom.find(".lh-gauge__percentage",b);d.textContent=c.toString();null===a.score&&(d.textContent="?",d.title=Util.UIStrings.errorLabel);this.dom.find(".lh-gauge__label",b).textContent=a.title;return b}_auditHasWarning(a){return!(!a.result.warnings||!a.result.warnings.length)}_getClumpIdForAuditRef(a){const b=a.result.scoreDisplayMode;return"manual"===b||"notApplicable"===b?b:Util.showAsPassed(a.result)?this._auditHasWarning(a)?"warning":"passed":"failed"}render(a,
b={}){const c=this.dom.createElement("div","lh-category");this.createPermalinkSpan(c,a.id);c.appendChild(this.renderCategoryHeader(a,b));var d=new Map;d.set("failed",[]);d.set("warning",[]);d.set("manual",[]);d.set("passed",[]);d.set("notApplicable",[]);for(const e of a.auditRefs){const f=this._getClumpIdForAuditRef(e),g=d.get(f);g.push(e);d.set(f,g)}for(const [e,f]of d)0!==f.length&&("failed"===e?(d=this.renderUnexpandableClump(f,b),d.classList.add("lh-clump--failed"),c.appendChild(d)):(d="manual"===
e?a.manualDescription:void 0,d=this.renderClump(e,{auditRefs:f,description:d}),c.appendChild(d)));return c}createPermalinkSpan(a,b){a=this.dom.createChildOf(a,"span","lh-permalink");a.id=b}}"undefined"!==typeof module&&module.exports?module.exports=CategoryRenderer:self.CategoryRenderer=CategoryRenderer;/*

 Copyright 2018 Google Inc. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS-IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
const getUniqueSuffix=(()=>{let a=0;return function(){return a++}})();
class PwaCategoryRenderer extends CategoryRenderer{render(a,b={}){const c=this.dom.createElement("div","lh-category");this.createPermalinkSpan(c,a.id);c.appendChild(this.renderCategoryHeader(a,b));var d=a.auditRefs;const e=d.filter(f=>"manual"!==f.result.scoreDisplayMode);b=this._renderAudits(e,b);c.appendChild(b);d=d.filter(f=>"manual"===f.result.scoreDisplayMode);a=this.renderClump("manual",{auditRefs:d,description:a.manualDescription});c.appendChild(a);return c}renderScoreGauge(a,b){if(null===
a.score)return super.renderScoreGauge(a,b);const c=this.dom.cloneTemplate("#tmpl-lh-gauge--pwa",this.templateContext),d=this.dom.find(".lh-gauge--pwa__wrapper",c);d.href=`#${a.id}`;var e=c.querySelector("svg");if(!e)throw Error("no SVG element found in PWA score gauge template");PwaCategoryRenderer._makeSvgReferencesUnique(e);e=this._getGroupIds(a.auditRefs);const f=this._getPassingGroupIds(a.auditRefs);if(f.size===e.size)d.classList.add("lh-badged--all");else for(const g of f)d.classList.add(`lh-badged--${g}`);
this.dom.find(".lh-gauge__label",c).textContent=a.title;d.title=this._getGaugeTooltip(a.auditRefs,b);return c}_getGroupIds(a){a=a.map(b=>b.group).filter(b=>!!b);return new Set(a)}_getPassingGroupIds(a){const b=this._getGroupIds(a);for(const c of a)!Util.showAsPassed(c.result)&&c.group&&b["delete"](c.group);return b}_getGaugeTooltip(a,b){var c=this._getGroupIds(a);const d=[];for(const f of c){var e=a.filter(l=>l.group===f);c=e.length;e=e.filter(l=>Util.showAsPassed(l.result)).length;const g=b[f].title;
d.push(`${g}: ${e}/${c}`)}return d.join(", ")}_renderAudits(a,b){b=this.renderUnexpandableClump(a,b);a=this._getPassingGroupIds(a);for(const c of a)a=this.dom.find(`.lh-audit-group--${c}`,b),a.classList.add("lh-badged");return b}static _makeSvgReferencesUnique(a){var b=a.querySelector("defs");if(b){var c=getUniqueSuffix();b=b.querySelectorAll("[id]");for(const e of b){var d=e.id;b=`${d}-${c}`;e.id=b;const f=a.querySelectorAll(`use[href="#${d}"]`);for(const g of f)g.setAttribute("href",`#${b}`);d=
a.querySelectorAll(`[fill="url(#${d})"]`);for(const g of d)g.setAttribute("fill",`url(#${b})`)}}}}"undefined"!==typeof module&&module.exports?module.exports=PwaCategoryRenderer:self.PwaCategoryRenderer=PwaCategoryRenderer;class PerformanceCategoryRenderer extends CategoryRenderer{_renderMetric(a){var b=this.dom.cloneTemplate("#tmpl-lh-metric",this.templateContext);const c=this.dom.find(".lh-metric",b);c.id=a.result.id;var d=Util.calculateRating(a.result.score,a.result.scoreDisplayMode);c.classList.add(`lh-metric--${d}`);d=this.dom.find(".lh-metric__title",b);d.textContent=a.result.title;d=this.dom.find(".lh-metric__value",b);d.textContent=a.result.displayValue||"";b=this.dom.find(".lh-metric__description",b);b.appendChild(this.dom.convertMarkdownLinkSnippets(a.result.description));
"error"===a.result.scoreDisplayMode&&(b.textContent="",d.textContent="Error!",b=this.dom.createChildOf(b,"span"),b.textContent=a.result.errorMessage||"Report error: no metric information");return c}_renderOpportunity(a,b){var c=this.dom.cloneTemplate("#tmpl-lh-opportunity",this.templateContext);c=this.populateAuditValues(a,c);c.id=a.result.id;if(!a.result.details||"error"===a.result.scoreDisplayMode)return c;const d=a.result.details;if("opportunity"!==d.type)return c;const e=this.dom.find(".lh-audit__display-text",
c);b=`${d.overallSavingsMs/b*100}%`;this.dom.find(".lh-sparkline__bar",c).style.width=b;e.textContent=Util.formatSeconds(d.overallSavingsMs,.01);a.result.displayValue&&(a=a.result.displayValue,this.dom.find(".lh-load-opportunity__sparkline",c).title=a,e.title=a);return c}_getWastedMs(a){if(a.result.details&&"opportunity"===a.result.details.type){a=a.result.details;if("number"!==typeof a.overallSavingsMs)throw Error("non-opportunity details passed to _getWastedMs");return a.overallSavingsMs}return Number.MIN_VALUE}render(a,
b,c){const d=this.dom.createElement("div","lh-category");if("PSI"===c){var e=this.dom.createElement("div","lh-score__gauge");e.appendChild(this.renderScoreGauge(a,b));d.appendChild(e)}else this.createPermalinkSpan(d,a.id),d.appendChild(this.renderCategoryHeader(a,b));e=this.renderAuditGroup(b.metrics);var f=this.dom.cloneTemplate("#tmpl-lh-metrics-toggle",this.templateContext);f=this.dom.find(".lh-metrics-toggle",f);e.append(...f.childNodes);var g=a.auditRefs.filter(h=>"metrics"===h.group);f=g.filter(h=>
3<=h.weight);g=g.filter(h=>3>h.weight);const l=this.dom.createChildOf(e,"div","lh-columns"),n=this.dom.createChildOf(l,"div","lh-column"),r=this.dom.createChildOf(l,"div","lh-column");f.forEach(h=>{n.appendChild(this._renderMetric(h))});g.forEach(h=>{r.appendChild(this._renderMetric(h))});"PSI"!==c&&(c=this.dom.createChildOf(e,"div","lh-metrics__disclaimer"),f=this.dom.convertMarkdownLinkSnippets(Util.UIStrings.varianceDisclaimer),c.appendChild(f));e.classList.add("lh-audit-group--metrics");d.appendChild(e);
e=this.dom.createChildOf(d,"div","lh-filmstrip-container");(c=(c=a.auditRefs.find(h=>"screenshot-thumbnails"===h.id))&&c.result)&&c.details&&(e.id=c.id,(c=this.detailsRenderer.render(c.details))&&e.appendChild(c));(c=a.auditRefs.find(h=>"performance-budget"===h.id))&&c.result.details&&(e=this.detailsRenderer.render(c.result.details))&&(e.id=c.id,e.classList.add("lh-audit"),c=this.renderAuditGroup(b.budgets),c.appendChild(e),c.classList.add("lh-audit-group--budgets"),d.appendChild(c));e=a.auditRefs.filter(h=>
"load-opportunities"===h.group&&!Util.showAsPassed(h.result)).sort((h,p)=>this._getWastedMs(p)-this._getWastedMs(h));if(e.length){c=e.map(t=>this._getWastedMs(t));c=Math.max(...c);const h=Math.max(1E3*Math.ceil(c/1E3),2E3),p=this.renderAuditGroup(b["load-opportunities"]);c=this.dom.cloneTemplate("#tmpl-lh-opportunity-header",this.templateContext);this.dom.find(".lh-load-opportunity__col--one",c).textContent=Util.UIStrings.opportunityResourceColumnLabel;this.dom.find(".lh-load-opportunity__col--two",
c).textContent=Util.UIStrings.opportunitySavingsColumnLabel;c=this.dom.find(".lh-load-opportunity__header",c);p.appendChild(c);e.forEach(t=>p.appendChild(this._renderOpportunity(t,h)));p.classList.add("lh-audit-group--load-opportunities");d.appendChild(p)}e=a.auditRefs.filter(h=>"diagnostics"===h.group&&!Util.showAsPassed(h.result)).sort((h,p)=>{h="informative"===h.result.scoreDisplayMode?100:Number(h.result.score);p="informative"===p.result.scoreDisplayMode?100:Number(p.result.score);return h-p});
if(e.length){const h=this.renderAuditGroup(b.diagnostics);e.forEach(p=>h.appendChild(this.renderAudit(p)));h.classList.add("lh-audit-group--diagnostics");d.appendChild(h)}a=a.auditRefs.filter(h=>("load-opportunities"===h.group||"diagnostics"===h.group)&&Util.showAsPassed(h.result));if(!a.length)return d;b={auditRefs:a,groupDefinitions:b};b=this.renderClump("passed",b);d.appendChild(b);return d}}
"undefined"!==typeof module&&module.exports?module.exports=PerformanceCategoryRenderer:self.PerformanceCategoryRenderer=PerformanceCategoryRenderer;class ReportRenderer{constructor(a){this._dom=a;this._templateContext=this._dom.document()}setTemplateContext(a){this._templateContext=a}_renderReportTopbar(a){const b=this._dom.cloneTemplate("#tmpl-lh-topbar",this._templateContext),c=this._dom.find(".lh-topbar__url",b);c.href=c.textContent=a.finalUrl;return b}_renderReportHeader(){const a=this._dom.cloneTemplate("#tmpl-lh-heading",this._templateContext),b=this._dom.cloneTemplate("#tmpl-lh-scores-wrapper",this._templateContext),c=this._dom.find(".lh-scores-wrapper-placeholder",
a);c.parentNode.replaceChild(b,c);return a}_renderReportFooter(a){const b=this._dom.cloneTemplate("#tmpl-lh-footer",this._templateContext),c=this._dom.find(".lh-env__items",b);c.id="runtime-settings";const d=Util.getEnvironmentDisplayValues(a.configSettings||{});[{name:"URL",description:a.finalUrl},{name:"Fetch time",description:Util.formatDateTime(a.fetchTime)},...d,{name:"User agent (host)",description:a.userAgent},{name:"User agent (network)",description:a.environment&&a.environment.networkUserAgent},
{name:"CPU/Memory Power",description:a.environment&&a.environment.benchmarkIndex.toFixed(0)}].forEach(e=>{if(e.description){var f=this._dom.cloneTemplate("#tmpl-lh-env__items",c);this._dom.find(".lh-env__name",f).textContent=e.name;this._dom.find(".lh-env__description",f).textContent=e.description;c.appendChild(f)}});this._dom.find(".lh-footer__version",b).textContent=a.lighthouseVersion;return b}_renderReportWarnings(a){if(!a.runWarnings||0===a.runWarnings.length)return this._dom.createElement("div");
const b=this._dom.cloneTemplate("#tmpl-lh-warnings--toplevel",this._templateContext);var c=this._dom.find(".lh-warnings__msg",b);c.textContent=Util.UIStrings.toplevelWarningsMessage;c=this._dom.find("ul",b);for(const d of a.runWarnings)a=c.appendChild(this._dom.createElement("li")),a.textContent=d;return b}_renderScoreGauges(a,b,c){const d=[],e=[],f=[];for(const g of Object.values(a.categories)){const l=c[g.id]||b,n=l.renderScoreGauge(g,a.categoryGroups||{});Util.isPluginCategory(g.id)?f.push(n):
l.renderScoreGauge===b.renderScoreGauge?d.push(n):e.push(n)}return[...d,...e,...f]}_renderReport(a){var b=new DetailsRenderer(this._dom),c=new CategoryRenderer(this._dom,b);c.setTemplateContext(this._templateContext);const d={performance:new PerformanceCategoryRenderer(this._dom,b),pwa:new PwaCategoryRenderer(this._dom,b)};Object.values(d).forEach(h=>{h.setTemplateContext(this._templateContext)});b=this._dom.createElement("div");b.appendChild(this._renderReportHeader());const e=this._dom.createElement("div",
"lh-container"),f=this._dom.createElement("div","lh-report");f.appendChild(this._renderReportWarnings(a));var g,l=1===Object.keys(a.categories).length;l?b.classList.add("lh-header--solo-category"):g=this._dom.createElement("div","lh-scores-header");if(g){l=this._dom.cloneTemplate("#tmpl-lh-scorescale",this._templateContext);var n=this._dom.find(".lh-scores-container",b);g.append(...this._renderScoreGauges(a,c,d));n.appendChild(g);n.appendChild(l);g=this._dom.createElement("div","lh-sticky-header");
g.append(...this._renderScoreGauges(a,c,d));e.appendChild(g)}g=f.appendChild(this._dom.createElement("div","lh-categories"));for(var r of Object.values(a.categories))l=d[r.id]||c,n=l.dom.createChildOf(g,"div","lh-category-wrapper"),n.appendChild(l.render(r,a.categoryGroups));c=this._dom.createFragment();r=this._renderReportTopbar(a);c.appendChild(r);c.appendChild(e);e.appendChild(b);e.appendChild(f);f.appendChild(this._renderReportFooter(a));return c}}ReportRenderer._UIStringsStash={};
"undefined"!==typeof module&&module.exports?module.exports=ReportRenderer:self.ReportRenderer=ReportRenderer;/*
 Copyright 2019 Google Inc. All Rights Reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/
const LineVisibility={ALWAYS:0,WHEN_COLLAPSED:1,WHEN_EXPANDED:2},LineContentType={CONTENT_NORMAL:0,CONTENT_HIGHLIGHTED:1,PLACEHOLDER:2,MESSAGE:3},classNamesByContentType={[LineContentType.CONTENT_NORMAL]:["lh-snippet__line--content"],[LineContentType.CONTENT_HIGHLIGHTED]:["lh-snippet__line--content","lh-snippet__line--content-highlighted"],[LineContentType.PLACEHOLDER]:["lh-snippet__line--placeholder"],[LineContentType.MESSAGE]:["lh-snippet__line--message"]};
function getLineAndPreviousLine(a,b){return{line:a.find(c=>c.lineNumber===b),previousLine:a.find(c=>c.lineNumber===b-1)}}function getMessagesForLineNumber(a,b){return a.filter(c=>c.lineNumber===b)}
class SnippetRenderer{static renderHeader(a,b,c,d,e){var f=Util.filterRelevantLines(c.lines,c.lineMessages,2);f=f.length<c.lines.length;b=a.cloneTemplate("#tmpl-lh-snippet__header",b);a.find(".lh-snippet__title",b).textContent=c.title;const {snippetCollapseButtonLabel:g,snippetExpandButtonLabel:l}=Util.UIStrings;a.find(".lh-snippet__btn-label-collapse",b).textContent=g;a.find(".lh-snippet__btn-label-expand",b).textContent=l;const n=a.find(".lh-snippet__toggle-expand",b);f?n.addEventListener("click",
()=>e()):n.remove();c.node&&a.isDevTools()&&(a=a.find(".lh-snippet__node",b),a.appendChild(d.renderNode(c.node)));return b}static renderSnippetLine(a,b,{content:c,lineNumber:d,truncated:e,contentType:f,visibility:g}){b=a.cloneTemplate("#tmpl-lh-snippet__line",b);b=a.find(".lh-snippet__line",b);const {classList:l}=b;classNamesByContentType[f].forEach(n=>l.add(n));g===LineVisibility.WHEN_COLLAPSED?l.add("lh-snippet__show-if-collapsed"):g===LineVisibility.WHEN_EXPANDED&&l.add("lh-snippet__show-if-expanded");
c+=e?"\u2026":"";e=a.find(".lh-snippet__line code",b);f===LineContentType.MESSAGE?e.appendChild(a.convertMarkdownLinkSnippets(c)):e.textContent=c;a.find(".lh-snippet__line-number",b).textContent=d.toString();return b}static renderMessage(a,b,c){return SnippetRenderer.renderSnippetLine(a,b,{lineNumber:" ",content:c.message,contentType:LineContentType.MESSAGE})}static renderOmittedLinesPlaceholder(a,b,c){return SnippetRenderer.renderSnippetLine(a,b,{lineNumber:"\u2026",content:"",visibility:c,contentType:LineContentType.PLACEHOLDER})}static renderSnippetContent(a,
b,c){const d=a.cloneTemplate("#tmpl-lh-snippet__content",b),e=a.find(".lh-snippet__snippet-inner",d);c.generalMessages.forEach(f=>e.append(SnippetRenderer.renderMessage(a,b,f)));e.append(SnippetRenderer.renderSnippetLines(a,b,c));return d}static renderSnippetLines(a,b,c){const {lineMessages:d,generalMessages:e,lineCount:f,lines:g}=c;c=Util.filterRelevantLines(c.lines,c.lineMessages,2);const l=0<e.length&&0===d.length,n=a.createFragment();var r=!1;for(let t=1;t<=f;t++){const {line:v,previousLine:A}=
getLineAndPreviousLine(g,t),{line:k,previousLine:m}=getLineAndPreviousLine(c,t);var h=!!k,p=!!m;p&&!h&&(r=!0);h&&r&&(n.append(SnippetRenderer.renderOmittedLinesPlaceholder(a,b,LineVisibility.WHEN_COLLAPSED)),r=!1);h=!v&&!!A;p=!v&&1===t;if(h||p)r=(r=!c.some(q=>q.lineNumber>t))||1===t,n.append(SnippetRenderer.renderOmittedLinesPlaceholder(a,b,r?LineVisibility.WHEN_EXPANDED:LineVisibility.ALWAYS)),r=!1;v&&(h=getMessagesForLineNumber(d,t),p=0<h.length||l,p=Object.assign({},v,{contentType:p?LineContentType.CONTENT_HIGHLIGHTED:
LineContentType.CONTENT_NORMAL,visibility:k?LineVisibility.ALWAYS:LineVisibility.WHEN_EXPANDED}),n.append(SnippetRenderer.renderSnippetLine(a,b,p)),h.forEach(q=>{n.append(SnippetRenderer.renderMessage(a,b,q))}))}return n}static render(a,b,c,d){b=a.cloneTemplate("#tmpl-lh-snippet",b);const e=a.find(".lh-snippet",b);d=SnippetRenderer.renderHeader(a,b,c,d,()=>e.classList.toggle("lh-snippet--expanded"));a=SnippetRenderer.renderSnippetContent(a,b,c);e.append(d,a);return e}}
"undefined"!==typeof module&&module.exports?module.exports=SnippetRenderer:self.SnippetRenderer=SnippetRenderer;function prepareLabData(a,b){var c="string"===typeof a?JSON.parse(a):a;b=new DOM(b);b.resetTemplates();var d=Util.prepareReportResult(c);a=d.categories.performance;if(!a)throw Error("No performance category. Can't make lab data section");if(!d.categoryGroups)throw Error("No category groups found.");d.categoryGroups.metrics.title=c.i18n.rendererFormattedStrings.labDataTitle;d.categoryGroups.metrics.description=c.i18n.rendererFormattedStrings.lsPerformanceCategoryDescription;c=new PerformanceCategoryRenderer(b,
new DetailsRenderer(b));c=c.render(a,d.categoryGroups,"PSI");d=b.find(".lh-score__gauge",c);d.remove();var e=b.find(".lh-gauge__wrapper",d);e.classList.add("lh-gauge__wrapper--huge");e.removeAttribute("href");a=_getFinalScreenshot(a);e=b.cloneTemplate("#tmpl-lh-scorescale",b.document());b=b.find(".lh-scorescale",e);return{scoreGaugeEl:d,perfCategoryEl:c,finalScreenshotDataUri:a,scoreScaleEl:b}}
function _getFinalScreenshot(a){return(a=a.auditRefs.find(b=>"final-screenshot"===b.id))&&a.result&&"error"!==a.result.scoreDisplayMode?a.result.details.data:null}"undefined"!==typeof module&&module.exports?module.exports=prepareLabData:self.prepareLabData=prepareLabData;
